#!/bin/bash

# Docker-CE and Docker compose installation script.
set -euo pipefail

remove_old_docker() {
  # Delete old version docker
  sudo apt-get remove docker docker-engine docker.io
}

add_docker_repo_gpg_key() {
  # Trust Docker's GPG public key
  curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo apt-key add -
}

add_docker_repo() {
  # Add Docker-CE software library
  add_docker_repo_gpg_key
  sudo add-apt-repository "deb [arch=amd64] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
}

install_docker_ce() {
  sudo apt-get update
  # Install dependencies
  sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
  sudo apt-get install docker-ce
}

install_docker_compose() {
  while read -p "Do you need to install Docker Compose? [Y/N]" -r install_flag; do
    case $install_flag in
    [Yy])
      sudo apt-get install docker-compose-plugin
      ;;
    [Nn])
      # do nothing
      ;;
    *)
      echo "Unresolved value: ${GLOBAL_FLAG}, please try again." >&2
      continue
      ;;
    esac
    break
  done
}

remove_old_docker
add_docker_repo
install_docker_ce
install_docker_compose
